/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thjava;

/**
 *
 * @author Admin
 */
public class login_340 extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login_340() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_340 = new javax.swing.JLabel();
        jTextField1_340 = new javax.swing.JTextField();
        jLabel2_340 = new javax.swing.JLabel();
        jTextField2_340 = new javax.swing.JTextField();
        jLabel3_340 = new javax.swing.JLabel();
        jTextField3_340 = new javax.swing.JTextField();
        jButton1_340 = new javax.swing.JButton();
        jButton2_340 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        jLabel1_340.setText("User name:");
        getContentPane().add(jLabel1_340);
        getContentPane().add(jTextField1_340);

        jLabel2_340.setText("Password:");
        getContentPane().add(jLabel2_340);
        getContentPane().add(jTextField2_340);

        jLabel3_340.setText("Confirm pasword:");
        getContentPane().add(jLabel3_340);
        getContentPane().add(jTextField3_340);

        jButton1_340.setText("Login");
        getContentPane().add(jButton1_340);

        jButton2_340.setText("Register");
        getContentPane().add(jButton2_340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_340.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_340.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_340.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_340.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_340().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_340;
    private javax.swing.JButton jButton2_340;
    private javax.swing.JLabel jLabel1_340;
    private javax.swing.JLabel jLabel2_340;
    private javax.swing.JLabel jLabel3_340;
    private javax.swing.JTextField jTextField1_340;
    private javax.swing.JTextField jTextField2_340;
    private javax.swing.JTextField jTextField3_340;
    // End of variables declaration//GEN-END:variables
}
